
name: Integration check

on:
  pull_request:
    branches: [ main ]

jobs:

  integration_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.5

      - name: Install ğŸ”§
        run: yarn install --frozen-lockfile

      - name: Lint ğŸ‘•
        run: yarn lint

      - name: Test ğŸ§ª
        run: yarn test

      - name: Build ğŸ‘·
        run: yarn build
